# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjcxYTNmZWI5Y2FiOGI1ZWNiODRkNjI1NmRjODliZDIyYjRhOTZjZGQ4MmFiMWU1MDdiZjY4MzA0ZDU5ZTQ0MTk2MDYwYzU2MTQ5OGU1MDYxOTRlNWQzNTMxZWEyZDU4NjBlZjFkZmQwZDdmNzQyNTQ3NzQxODc0ODRhODE1Mzc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
