name: FINACE ERP GATEWAY CI
on: [push, pull_request]
jobs:
    pipeline:
        name: ERP Gate pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '11.x'
            - name: Run backend test
              working-directory: ./erp-gate
              run: |
                  chmod +x mvnw
                  npm run ci:backend:test
            - name: Package application
              working-directory: ./erp-gate
              run: npm run java:jar:prod
            - name: Build and publish docker image
              working-directory: ./erp-gate
              if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
              run:
                  ./mvnw -ntp jib:build -Djib.to.image=ghacupha/erp-gate:0.0.1-SNAPSHOT -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}"
