name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: ERP Server pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            ERP_SYSTEM_PROD_DB: "${{ secrets.ERP_SYSTEM_PROD_DB }}"
            SPRING_DATA_JEST_URI: "${{ secrets.SPRING_DATA_JEST_URI }}"
            ERP_SYSTEM_DEV_DB: "${{ secrets.ERP_SYSTEM_DEV_DB }}"
            ERP_SYSTEM_PORT: "${{ secrets.ERP_SYSTEM_PORT }}"
            PG_DATABASE_DEV_USER: "${{ secrets.PG_DATABASE_DEV_USER }}"
            PG_DATABASE_PROD_USER: "${{ secrets.PG_DATABASE_PROD_USER }}"
            PG_DATABASE_DEV_PASSWORD: "${{ secrets.PG_DATABASE_DEV_PASSWORD }}"
            PG_DATABASE_PROD_PASSWORD: "${{ secrets.PG_DATABASE_PROD_PASSWORD }}"
            LOCAL_PG_SERVER: "${{ secrets.LOCAL_PG_SERVER }}"
            ERP_SYSTEM_DEV_PORT: "${{ secrets.ERP_SYSTEM_DEV_PORT }}"
            ERP_SYSTEM_PROD_PORT: "${{ secrets.ERP_SYSTEM_PROD_PORT }}"
            ERP_SYSTEM_PROD_MAIL_BASE_URL: "${{ secrets.ERP_SYSTEM_PROD_MAIL_BASE_URL }}"
            ERP_SYSTEM_DEV_MAIL_BASE_URL: "${{ secrets.ERP_SYSTEM_DEV_MAIL_BASE_URL }}"
            SECURITY_AUTHENTICATION_JWT_BASE64_SECRET: "${{ secrets.SECURITY_AUTHENTICATION_JWT_BASE64_SECRET }}"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Run backend test
              working-directory: ./erp-system
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean verify
            - name: Package application
              working-directory: ./erp-system
              run: ./mvnw -ntp package -Pprod -DskipTests
            # log in to docker
            - name: Login to Docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and publish docker image
              working-directory: ./erp-system
              run: ./mvnw -ntp jib:build -Djib.to.image=ghacupha/erp-system:0.0.1-SNAPSHOT -Djib.to.auth.username="${{ secrets.DOCKERHUB_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKERHUB_TOKEN }}"
